### PR TITLE
Support image_optim proxy

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Support `image_optim` proxy to optimize images and allow that process to be configured from configuration file. Related issue #297

### CODE REVIEW

**Comment by envygeeks** [comment]
Will review tonight!

**Comment by envygeeks** [comment]
Can you rebase please? Thanks!

**Comment by alexey-pelykh** [comment]
@envygeeks done

**Comment by envygeeks** [comment]
Thanks :heart:

**Pull request merged**
