### PR TITLE
RSpec: addons/proxies -> proxies

### PR DESCRIPTION
**Pull request by spudowiar**
Should have been moved in ae36183d3fd658785115ecc0d7b4c75882f41571

### CODE REVIEW

**Comment by envygeeks** [comment]
It seems this pull request doesn't do what it states? The changes here remove our Liquid processor which is a no-go.  It also removes files that were conciously placed for organization and removes our very explicit require setup to a more ambiguously defined approach.  I'm not aligned with these changes.

**Comment by spudowiar** [comment]
In ae36183d3fd658785115ecc0d7b4c75882f41571 `lib/jekyll/assets/addons/proxies` was moved to `lib/jekyll/assets/proxies`. This is intended to mirror that in `spec/tests`. No files are removed, only renamed.

**Comment by spudowiar** [comment]
@envygeeks Ah! I see what you've done :) The commit I have linked to is a commit that is in `master` that **you** made a long time ago. That's not the commit I am attempting to PR.

**Comment by spudowiar** [comment]
@envygeeks so is this going to be merged? It's just a simple file rename.

**Pull request merged**
