### PR TITLE
Fix auto image size reading

### LINKED ISSUE #381: FastImage.size goes into infinite loop using Pathutil.read
I've spent a while tracking this down but there seems to be some incompatibility with the `read` method exposed by `Pathutil` and what [`FastImage.fetch_using_read`](https://github.com/sdsykes/fastimage/blob/v2.0.1/lib/fastimage.rb#L312-L334) expects: 
```rb
  def fetch_using_read(readable)
    # Pathnames respond to read, but always return the first
    # chunk of the file unlike an IO (even though the
    # docuementation for it refers to IO). Need to supply
    # an offset in this case.
    if readable.is_a?(Pathname)
      read_fiber = Fiber.new do
        offset = 0
        while str = readable.read(LocalFileChunkSize, offset)
          Fiber.yield str
          offset += LocalFileChunkSize
        end
      end
    else
      read_fiber = Fiber.new do
        while str = readable.read(LocalFileChunkSize)
          Fiber.yield str
        end
      end
    end

    parse_packets FiberStream.new(read_fiber)
  end
```

It seems like `Pathutil.read` and `Pathname.read` probably operate the same way: not keeping the file open and therefore requiring an offset be passed.

Here's a simple example I was testing with:
```rb
require 'fastimage'
require 'pathutil'

# This will return
path = './episode_1.jpg'
puts FastImage.new(path).size

# This never returns
path = Pathutil.new('./episode_1.jpg')
puts FastImage.new(path).size
```

### PR DESCRIPTION
**Pull request by drewish**
FastImage assumes that if image argument responds to `read` that it will act like `IO#read` and subsequent calls will advance through the stream. [`Pathutil#read`](https://github.com/envygeeks/pathutil/blob/master/lib/pathutil.rb#L496-L509) uses `File::read` which reopens the file each time causing infinite loops. If we just pass in a simple string, FastImage will use `File::open` and avoid the issue.

Fixes #381

### CODE REVIEW

**Comment by envygeeks** [comment]
Well, File.read is IO.read, we do accept an offset though, just like File/IO.read would, since we pass arguments right into File.read.  Unless they are looking for us to advance the offset for them, which I can certainly do and would probably fix this bug. However, in the meantime this is a great fix, thanks!

**Comment by drewish** [comment]
Yeah my read of their code is that they expect the file to stay open and have the pointer advance with each read. Hence their special case for Pathname because it doesn't auto advance.

**Comment by envygeeks** [comment]
Their logic is a bit broken and backwards. I don't know if I should fix it there or in Pathutil.

**Comment by drewish** [comment]
Yeah agreed, that's why I decided to side step it and just pass in a string.

**Pull request merged**
