### PR TITLE
Configure autoprefixer via asset_config

### PR DESCRIPTION
**Pull request by dommmel**
E.g. (_config.yml):
 
    assets:
      autoprefixer:
          browsers: ["> 1%","last 4 versions","IE > 8"]

### CODE REVIEW

**Comment by envygeeks** [comment]
This is a no, unless you are willing to build a wrapper for any and all addons that accept options to whitelist only acceptable options.  Because of our want to be included on Github pages, blindly accepting options is unacceptable because they can change their options at any given time and create a gap of which I am not willing to accept and have to account for later.

**Comment by envygeeks** [comment]
Sorry, I did not explain what this gap could be: the filesystem.  We do not want people to include files outside of Jekyll's root.  Whether autoprefixer has that option right now or not is not relevant to the need to prevent it in the future without me having to constantly keep track of every single little change it makes, because as it stands right now we take a audit yourself approach to addons since we don't have any explicit addons that are not sprockets.

**Comment by dommmel** [comment]
Thanks for the clarification (and the gem itself of course!). Seems to make a lot of sense. I am not sure of understand 100% of it though. 

* What if autoprefixer decides to start parsing a config at say ``~/.autoprefixerc``? Or is this prevented by "sprocket mode" (no clue how a sprocket is defined to be honest) ?
* Is there a way to configure autoprefixer (or any other addon for that matter)?

**Comment by envygeeks** [comment]
It does already try to include that file but only on Rails, that was a problem I did spot when I chose to use this one as an addon but something I planned to deal with when I was building in the option whitelist.  It was ultimately set to low-priority (the including of the file) because it only did it for Rails.

That was a passive decision because it was only done for Rails, but this pull is an active decision because it also has the "to" and "from" options (how and whether or not you can get to them from those options is pretty unclear to me right now as I didn't audit the source that closely) but I did notice those options which is what prevented me from just allowing it in the first place.

At this time there is no ability to do what you wish but I'll consider what to do over the next few days as you've brought up some points that make me think about what our policy should be, maybe I shouldn't care about addons and just disable them if Jekyll is in safe-mode and then merge this pull request, call it a day, that would be fair right?  Let me think about it and I'll get back to you.

**Comment by dommmel** [comment]
Seems like a good option to me. If the goal here is to be included on Github Pages I would speculate that Github will be trying to avoid cpu expensive tasks (e.g. imagemagick et. al.) anyway.

Thanks for your effort and your consideration

**Comment by envygeeks** [comment]
I have decided to shift my policy to that of the like from Jekyll.  From now on we will allow people to configure their plugins and just disable them in so-called "safe-mode" like @jekyll/core does it, this gives you ultimate flexibility and allows me to later seek inclusion in Github when I'm truly ready to ask seriously for them to consider it rather than give a preliminary overview.

In that light I've merged your pull and :heart: for the contribution!

**Comment by dommmel** [comment]
My pleasure!

**Pull request merged**
